name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Parcial

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # ðŸš¨ FORZAR .NET 8 PARA QUE TENGA PRIORIDAD SOBRE .NET 9
      - name: Force dotnet 8 to override system dotnet
        shell: pwsh
        run: |
          Write-Host "DotNet root: $Env:DOTNET_ROOT"
          $newPath = "$Env:DOTNET_ROOT;$Env:DOTNET_ROOT\tools;" + $Env:PATH
          echo "PATH=$newPath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Check SDK in use
        run: dotnet --info

      - name: Restore
        run: dotnet restore BadCleanArch.sln

      - name: Build
        run: dotnet build BadCleanArch.sln --no-restore -c Release

      - name: Test
        run: dotnet test BadCleanArch.sln --no-build -c Release --collect:"XPlat Code Coverage"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.projectKey=parcial"
            --define "sonar.organization=mazp73"
            --define "sonar.projectName=parcial"
            --define "sonar.sources=src"
            --define "sonar.host.url=https://sonarcloud.io"
            --define "sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml"
