name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required by SonarCloud

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Cambia si usas otra versiÃ³n

      - name: Restore dependencies
        run: dotnet restore ./src/BadCleanArch.sln

      - name: Build
        run: dotnet build ./src/BadCleanArch.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ./src/BadCleanArch.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=mazp73
            -Dsonar.projectKey=parcial
            -Dsonar.projectName=parcial
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
