name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Parcial

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ðŸ“Œ Instalar .NET 9 (Ãºnico SDK que vas a usar)
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Check dotnet version
        run: dotnet --info

      - name: Restore
        run: dotnet restore BadCleanArch.sln

      - name: Build
        run: dotnet build BadCleanArch.sln --no-restore -c Release

      - name: Test with coverage
        run: dotnet test BadCleanArch.sln --no-build -c Release --collect:"XPlat Code Coverage"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.projectKey=parcial
            --define sonar.organization=mazp73
            --define sonar.projectName=parcial
            --define sonar.sources=src
            --define sonar.host.url=https://sonarcloud.io
            --define sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
